/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gringrape.trie;

import org.junit.jupiter.api.Test;

import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;

class TrieTest {
    @Test
    void testIsWorking() {
        assertThat(1 + 1).isEqualTo(2);
    }

    @Test
    void creation() {
        new Trie();
    }

    @Test
    void insertionAndSearchWithOneWord() {
        var trie = new Trie();

        var word = "helloWorld";

        trie.insert(word);

        assertThat(trie.search("helloWorld")).isTrue();

        assertThat(trie.search("helloWorldd")).isFalse();

        assertThat(trie.search("hello")).isFalse();
    }

    @Test
    void testStartsWith() {
        var trie = new Trie();

        var word = "helloWorld";

        trie.insert(word);

        assertThat(trie.startsWith("hello")).isTrue();
    }

    @Test
    void reduceTest() {
        var sum = IntStream.rangeClosed(0, 10)
                .reduce(0, Integer::sum);

        assertThat(sum).isEqualTo(55);
    }
}
